### PR TITLE
Added marital_status error handling

### PR DESCRIPTION
**Pull request by colinbruce**
To do this, an error block is added to session and then re-loaded
on reloading the page.  On successful submission of the form, the
session variable is cleared.

I've added a proposal for feature tests by page to handle routing 
and error handling.  Happy to discuss, and possibly move back into
the uber feature tests if that is preferred.

This should probably be reviewed by:
@dotemacs as usual,
@axemonkey to check my css usage, and 
@leighmoney to check my words!

### CODE REVIEW

**Comment by colinbruce** [comment]
We'll have to ignore codeclimate for a while... they have upgraded to rubocop 37.2 and are ignoring the version in our Gemfile.  I'll disable it on Monday until the rubocop situation is sorted.

**Comment by dotemacs** [comment]
Looks good, go!

**Comment by axemonkey** [comment]
Yep, all looking good to me!

**Comment by colinbruce** [comment]
Rebased to update yml files

**Pull request merged**
