### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by dotemacs**
RSpec setup added

### CODE REVIEW

**Comment by novotnyjakub** [comment]
:+1: 

On RSpec setup, I'd just suggest not use `capybara-webkit` if we're planning to use `nightwatch`. Or if we want to do all testing in RSpec we could look at `poltergeist` which can drive `phantomjs` using the same tests. But we're not at this decision just yet, I suppose.

**Comment by dotemacs** [comment]
@axemonkey what are your thoughts?

**Comment by axemonkey** [comment]
My thoughts are that we'll probably want to do most of our testing with something like `capybara` or whatever is normally used, and reserve `nightwatch` solely for testing browser-based (JS) interactions. Nightwatch testing is valuable for testing JS in browser, but is slow and requires a local rails app to be spun up, so I'd like to use it only for things that just aren't testable otherwise.

**Comment by axemonkey** [comment]
`RSpec` is fast, `jasmine` is fast for unit-testable JS, and `Nightwatch` is slow but necessary to test stuff that the first two can't test.

**Comment by novotnyjakub** [comment]
The thing is `RSpec` is fast, but for functional tests it depends on what browser backend do we use for it. `Capybara-webkit` is incredibly slow, I think it's faster to run on `Phantomjs`. So that's why I'm asking. Also if we want to re-use the same tests (or tagged subset) to run on `Browserstack` for cross browser testing, maybe we could do all with just `RSpec`..

**Comment by axemonkey** [comment]
Ah fair enough, I don't care what browser `RSpec` is testing. `Phantomjs` is fine by me - `Nightwatch` needs it anyway.

**Comment by dotemacs** [comment]
Going to merge this in. Since it's the start of the app, if any changes needed to be made, it won't be hard to twist it

**Comment by axemonkey** [comment]
:+1:

**Pull request merged**
