### PR TITLE
Styling for savings and investments page

### PR DESCRIPTION
**Pull request by axemonkey**
[Le Pivotal](https://www.pivotaltracker.com/story/show/113432433)

More of the same. Not sure why it says Question 2 of 14 though.

screen shot 2016-02-12 at 15 42 36

### CODE REVIEW

**Comment by dotemacs** [comment]
@axemonkey just going by the prototype numbering. The first form was marital_status, this one is the second...

**Comment by axemonkey** [comment]
It wasn't really the "2" I was questioning. :)

**Comment by axemonkey** [comment]
To clarify, I was just cheekily questioning the hardcoded "2 of 14", not the idea of having numbered questions. :+1:

**Comment by dotemacs** [comment]
Stunning. Merge.

**Pull request merged**
