### PR TITLE
Updated income guidance

### PR DESCRIPTION
**Pull request by leighmoney**
Added info on what should be included as income; added links to the
guide.

### CODE REVIEW

**Comment by leighmoney** [comment]
@axemonkey - could you please take a look at these income page copy additions when you can - see my piv update in: https://www.pivotaltracker.com/story/show/113911003

**Comment by axemonkey** [comment]
OK, laid out now. Top bit looky likey:
screen shot 2016-03-02 at 15 38 37

**Comment by axemonkey** [comment]
Bottom bit when JS is off:
screen shot 2016-03-02 at 15 46 53

**Comment by colinbruce** [comment]
Looks great, merge with pride

**Pull request merged**
