### PR TITLE
Remove Turbolinks

### PR DESCRIPTION
**Pull request by axemonkey**
Don't use Turbolinks.

### CODE REVIEW

**Comment by dotemacs** [comment]
+1 insightful.

Is it somewhat related to this PR: https://github.com/ministryofjustice/fr-staffapp/pull/537

**Comment by axemonkey** [comment]
Indeed it is. Turbolinks is a Bad Idea.

**Comment by dotemacs** [comment]
:hocho: :bomb: :moyai: 

I'll merge.

**Comment by axemonkey** [comment]
:racehorse: :dash:

**Pull request merged**
